# Generated by Django 4.1.3 on 2023-07-11 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name that helps you identify this key",
                        max_length=50,
                        verbose_name="API Key name",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(max_length=10, verbose_name="API Key prefix"),
                ),
                (
                    "public_key",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Public key"
                    ),
                ),
                (
                    "hashed_key",
                    models.CharField(max_length=255, verbose_name="Hashed private key"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave as empty for a non-expiring key.",
                        null=True,
                        verbose_name="Time at which the API Key expires",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        null=True, verbose_name="When the API key was last used"
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("read", "read"),
                            ("create", "create"),
                            ("update", "update"),
                            ("delete", "delete"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
            },
        ),
        migrations.CreateModel(
            name="APIKeyScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uw_api_keys.apikey",
                        verbose_name="API Key",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "operations",
                    models.ManyToManyField(
                        to="uw_api_keys.operationtype", verbose_name="Operation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity permission",
                "verbose_name_plural": "Entity permissions",
            },
        ),
        migrations.CreateModel(
            name="APIKeyLogEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Endpoint",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("read", "read"),
                            ("create", "create"),
                            ("update", "update"),
                            ("delete", "delete"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Operation",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Request headers"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Request meta-information"
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Request's body"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Log time"
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uw_api_keys.apikey",
                        verbose_name="API Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Log Event",
                "verbose_name_plural": "API Key Log Events",
            },
        ),
        migrations.AddField(
            model_name="apikey",
            name="scopes",
            field=models.ManyToManyField(
                help_text="The scopes that this key can access. Leave as empty to grant access to everything.",
                through="uw_api_keys.APIKeyScope",
                to="contenttypes.contenttype",
                verbose_name="Scopes",
            ),
        ),
    ]
