# Generated by Django 5.0.4 on 2024-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uw_api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="valid_origins",
            field=models.TextField(
                blank=True,
                help_text="A list of valid web origins for this key. Leave empty to allow all. Provide one per-line separated by commas.<br/> <b>Example:</b> <br/>http://localhost:5000,<br/>https://mydomain.com",
                null=True,
                verbose_name="Valid web origins",
            ),
        ),
    ]
