# Generated by Django 5.0.4 on 2024-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uw_api_keys", "0002_apikey_valid_origins"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="log_usage",
            field=models.BooleanField(
                default=None,
                help_text="Whether to log usage of this key. This overrides the global setting (Enabled).",
                null=True,
                verbose_name="Log usage",
            ),
        ),
    ]
